#!/usr/bin/env bun
import * as p from "@clack/prompts";
import ora from "ora";
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { DEFAULT_INSTRUCTION_PREFIX, readConfig } from "./lib/config";
import { generateCommitMessage } from "./lib/generate";
import { addPaths, displayPath, getChangedFiles, getDiffs, getRepoRoot, runGitStreaming } from "./lib/git";

function editInEditor(initial: string): string {
  const dir = mkdtempSync(path.join(os.tmpdir(), "committer-"));
  const file = path.join(dir, "COMMIT_EDITMSG");
  writeFileSync(file, initial);
  try {
    const editor = process.env.EDITOR || process.env.VISUAL || (process.platform === "win32" ? "notepad" : "vi");
    const result = spawnSync(editor, [file], { stdio: "inherit" });
    if (result.error) throw new Error(`Could not launch editor "${editor}": ${result.error.message}`);
    return readFileSync(file, "utf-8").trim();
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

export async function runCli(): Promise<void> {
  p.intro("committer -c");

  const repoRoot = await getRepoRoot().catch(() => null);
  if (repoRoot) p.log.info(displayPath(repoRoot));

  const config = await readConfig();
  if (!config || config.models.length === 0) {
    p.cancel("No AI provider configured. Run `committer` (TUI) to add one first.");
    process.exit(1);
  }

  const changedFiles = await getChangedFiles();
  if (changedFiles.length === 0) {
    p.cancel("No file(s) to commit.");
    process.exit(1);
  }

  const selected = await p.multiselect({
    message: "Select file(s) to commit",
    options: changedFiles.map((f) => ({ value: f.path, label: `${f.status} ${f.path}` })),
    initialValues: changedFiles.map((f) => f.path),
    required: true,
  });
  if (p.isCancel(selected)) {
    p.cancel("Cancelled.");
    process.exit(1);
  }

  const diffs = await getDiffs(selected as string[]);
  const combinedDiff = diffs.map((d) => d.diff).join("\n");
  p.log.info(`Sending ${combinedDiff.length} characters of diff to the AI`);

  let message: string | null = null;
  for (const model of config.models) {
    const spinner = ora(`Generating commit message... (${model.provider} - ${model.model})`).start();
    try {
      message = await generateCommitMessage(combinedDiff, model, config.instructionPrefix ?? DEFAULT_INSTRUCTION_PREFIX, config.instructionSuffix ?? "", config.maxRetries);
      spinner.succeed(`Generated by ${model.provider} - ${model.model}`);
      break;
    } catch (err) {
      spinner.fail(`Failed (${model.provider} - ${model.model}): ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  if (!message) {
    p.cancel("All AI models failed to generate a commit message.");
    process.exit(1);
  }

  for (;;) {
    p.note(message, "Commit message", { format: (line) => `\x1b[32m${line}\x1b[0m` });
    const action = await p.select({
      message: "Proceed?",
      options: [
        { value: "confirm", label: "Confirm" },
        { value: "edit", label: "Edit" },
        { value: "cancel", label: "Cancel" },
      ],
    });
    if (p.isCancel(action) || action === "cancel") {
      p.cancel("Cancelled.");
      process.exit(1);
    }
    if (action === "confirm") break;

    message = editInEditor(message);
    if (!message) {
      p.cancel("Empty commit message. Cancelled.");
      process.exit(1);
    }
  }

  const spinner = ora("Committing...").start();
  try {
    await addPaths(selected as string[], (line) => { spinner.text = line; });
    await runGitStreaming(["commit", "-m", message], (line) => { spinner.text = line; });
    spinner.succeed("Commit created");
  } catch (err) {
    spinner.fail(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }

  p.outro("Done.");
}
